/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiPotionFileRouteImport } from './routes/api/potion-file'
import { Route as ApiPotionLiveRouteImport } from './routes/api/potion-live'
import { Route as ApiPotionRpcRouteImport } from './routes/api/potion-rpc'
import { Route as STokenRouteImport } from './routes/s.$token'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPotionFileRoute = ApiPotionFileRouteImport.update({
  id: '/api/potion-file',
  path: '/api/potion-file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPotionLiveRoute = ApiPotionLiveRouteImport.update({
  id: '/api/potion-live',
  path: '/api/potion-live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPotionRpcRoute = ApiPotionRpcRouteImport.update({
  id: '/api/potion-rpc',
  path: '/api/potion-rpc',
  getParentRoute: () => rootRouteImport,
} as any)
const STokenRoute = STokenRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/potion-file': typeof ApiPotionFileRoute
  '/api/potion-live': typeof ApiPotionLiveRoute
  '/api/potion-rpc': typeof ApiPotionRpcRoute
  '/s/$token': typeof STokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/potion-file': typeof ApiPotionFileRoute
  '/api/potion-live': typeof ApiPotionLiveRoute
  '/api/potion-rpc': typeof ApiPotionRpcRoute
  '/s/$token': typeof STokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/potion-file': typeof ApiPotionFileRoute
  '/api/potion-live': typeof ApiPotionLiveRoute
  '/api/potion-rpc': typeof ApiPotionRpcRoute
  '/s/$token': typeof STokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/potion-file'
    | '/api/potion-live'
    | '/api/potion-rpc'
    | '/s/$token'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/potion-file'
    | '/api/potion-live'
    | '/api/potion-rpc'
    | '/s/$token'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/api/potion-file'
    | '/api/potion-live'
    | '/api/potion-rpc'
    | '/s/$token'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ApiPotionFileRoute: typeof ApiPotionFileRoute
  ApiPotionLiveRoute: typeof ApiPotionLiveRoute
  ApiPotionRpcRoute: typeof ApiPotionRpcRoute
  STokenRoute: typeof STokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/potion-file': {
      id: '/api/potion-file'
      path: '/api/potion-file'
      fullPath: '/api/potion-file'
      preLoaderRoute: typeof ApiPotionFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/potion-live': {
      id: '/api/potion-live'
      path: '/api/potion-live'
      fullPath: '/api/potion-live'
      preLoaderRoute: typeof ApiPotionLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/potion-rpc': {
      id: '/api/potion-rpc'
      path: '/api/potion-rpc'
      fullPath: '/api/potion-rpc'
      preLoaderRoute: typeof ApiPotionRpcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$token': {
      id: '/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof STokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ApiPotionFileRoute: ApiPotionFileRoute,
  ApiPotionLiveRoute: ApiPotionLiveRoute,
  ApiPotionRpcRoute: ApiPotionRpcRoute,
  STokenRoute: STokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
